title: Eduardo Damm  # Add a space after the period

logo: ED.png  # Use a relative path to logo image 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin 

email: damm@mail.com # Allow visitors to contact you
