title: Eduardo Damm  # Add a space after the period

logo: !(2.jpeg){:class="img-responsive"}  # Use a relative path to logo image 

description: Intelligence Officer. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin 

email: damm@mail.com # Allow visitors to contact you
